### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by BojanZivanovic** [hyperether/getgoing-android-java#38]
![Screenshot_20200211_093134_com hyperether getgoing](https://user-images.githubusercontent.com/49106915/74224014-3d0a4c80-4cb8-11ea-9005-4fb404b3ebd0.jpg)

user icon to be smaller, not in height logo

"View all" should be bolder

Blue rectangle (last exercise) shoud be also clickable, like "view all", reduce height 

Icons for walking, running, bicycling shoud be smaller, and only active icon to be bigger against them

Button "Get ready" shoud have blue shadow instead of black

Bicycling instead of cycling

**Comment by SlobodanPrijic** [comment]
@BojanZivanovic please check latest version
