### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by BojanZivanovic** [hyperether/getgoing-android-java#39]
![Screenshot_20200211_095036_com hyperether getgoing](https://user-images.githubusercontent.com/49106915/74224114-75118f80-4cb8-11ea-8fd7-fd2bccb07d39.jpg)

icons for weight and height are poorly scaled

In dialogs change green to blue

**Comment by SlobodanPrijic** [comment]
@BojanZivanovic please check latest version
